name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Build & Push Docker Image
      env:
        GITHUB_TOKEN: ${{ secrets.SPARK_GITHUB_TOKEN }}
      run: |
        docker build -t ghcr.io/tarunratan/yarn-demo-app:latest .
        docker login ghcr.io -u tarunratan -p "$TOKEN"
        docker push ghcr.io/tarunratan/yarn-demo-app:latest


